const express = require('express')
const router = require('./router')
const cors = require('cors')
const url = require("url")
const app = express()
app.use(cors())
app.use('/', router)
app.listen(3000)